// Mock data for Cuerate app development
// This simulates Firebase data structures
import {
  availableModels,
  availableMoodLabels,
  availableStyleTags,
  Collection,
  difficultyLevels,
  Notification,
  Prompt,
  User,
} from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    uid: 'user1',
    handle: 'soramaster',
    displayName: 'Alex Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHdvbWFufGVufDF8fHx8MTc3NTM3OTAyOXww&ixlib=rb-4.1.0&q=80&w=200',
    bio: 'AI video creator specializing in cinematic aerial shots',
    links: { x: '@alexchen', instagram: 'alexchen', youtube: 'alexchen' },
    primaryModels: ['Sora', 'Runway'],
    followers: 12500,
    following: 340,
    totalCopies: 4200,
    totalPrompts: 87,
    createdAt: new Date('2024-01-15'),
  },
  {
    uid: 'user2',
    handle: 'runwaypro',
    displayName: 'Jordan Rivera',
    avatarUrl: 'https://images.unsplash.com/photo-1554765345-6ad6a5417cde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMG1hbnxlbnwxfHx8fDE3NzUzNjAyNDB8MA&ixlib=rb-4.1.0&q=80&w=200',
    bio: 'Experimental video artist pushing AI boundaries',
    links: { instagram: 'jordanrivera', website: 'jordanrivera.com' },
    primaryModels: ['Runway', 'Kling', 'Pika'],
    followers: 8900,
    following: 210,
    totalCopies: 2800,
    totalPrompts: 63,
    createdAt: new Date('2024-02-01'),
  },
  {
    uid: 'currentUser',
    handle: 'yourhandle',
    displayName: 'Your Name',
    avatarUrl: 'https://images.unsplash.com/photo-1649589244330-09ca58e4fa64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHdvbWFufGVufDF8fHx8MTc3NTM3OTAyOXww&ixlib=rb-4.1.0&q=80&w=200',
    bio: 'AI video enthusiast exploring creative prompts',
    links: {},
    primaryModels: ['Sora'],
    followers: 342,
    following: 125,
    totalCopies: 89,
    totalPrompts: 12,
    createdAt: new Date('2024-03-10'),
  },
];

// Mock Prompts
export const mockPrompts: Prompt[] = [
  {
    id: 'prompt1',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video1.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635255073378-ac341396271b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaW5lbWF0aWMlMjBkcm9uZSUyMGFlcmlhbCUyMGxhbmRzY2FwZXxlbnwxfHx8fDE3NzU0NDAwMDh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'A sweeping aerial view of a misty mountain valley at golden hour, slow smooth camera movement pushing forward through low-hanging clouds revealing a winding river below, cinematic depth of field, warm color grading',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['cinematic', 'aerial', 'nature'],
    cameraNotes: 'anamorphic lens, slow dolly forward, shallow depth of field',
    moodLabel: 'Cinematic',
    difficulty: 'Intermediate',
    likes: 892,
    saves: 445,
    copies: 1240,
    forks: 23,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-05T14:30:00'),
  },
  {
    id: 'prompt2',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video2.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1610206682191-c18ea65162c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMGNvbG9yZnVsJTIwbW90aW9uJTIwYmx1cnxlbnwxfHx8fDE3NzU0NDAwMDh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Abstract flowing liquid colors morphing and blending in slow motion, neon pink and electric blue mixing with deep purple, high contrast lighting, macro close-up revealing intricate patterns',
    model: 'Runway',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['abstract', 'macro', 'slowmo'],
    cameraNotes: 'macro lens, 120fps slow motion, high-key lighting',
    moodLabel: 'Abstract',
    difficulty: 'Advanced',
    likes: 634,
    saves: 312,
    copies: 876,
    forks: 18,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-05T10:15:00'),
  },
  {
    id: 'prompt3',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video3.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1732644144489-b1974816d3c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMGNpdHklMjBuaWdodCUyMGxpZ2h0c3xlbnwxfHx8fDE3NzUzNDkzMzZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Time-lapse of a bustling city intersection at night, light trails from cars creating vibrant streaks of red and white, neon signs reflecting on wet pavement, dynamic urban energy',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['urban', 'timelapse', 'motion'],
    cameraNotes: 'locked tripod, long exposure simulation, wide angle',
    moodLabel: 'Dramatic',
    difficulty: 'Beginner',
    likes: 521,
    saves: 267,
    copies: 734,
    forks: 12,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-04T18:45:00'),
  },
  {
    id: 'prompt4',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video4.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1720110701672-a2ae3a95de0b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBmb3Jlc3QlMjBjaW5lbWF0aWN8ZW58MXx8fHwxNzc1NDQwMDA5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Sunlight filtering through dense forest canopy, god rays illuminating particles of dust and pollen floating in the air, gentle camera drift sideways through ancient trees',
    model: 'Kling',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['nature', 'cinematic', 'motion'],
    cameraNotes: 'gentle lateral tracking, soft diffused lighting',
    moodLabel: 'Naturalistic',
    difficulty: 'Intermediate',
    likes: 445,
    saves: 198,
    copies: 612,
    forks: 8,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-04T12:20:00'),
  },
  {
    id: 'prompt5',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video5.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1639843091483-b2564b0e477e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvY2VhbiUyMHdhdmVzJTIwc2xvdyUyMG1vdGlvbnxlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Massive ocean wave cresting in ultra slow motion, water droplets suspended in air catching sunlight like diamonds, transparent turquoise water texture visible, powerful yet graceful',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['slowmo', 'nature', 'cinematic'],
    cameraNotes: 'high-speed 240fps, close-up perspective, bright daylight',
    moodLabel: 'Dramatic',
    difficulty: 'Advanced',
    likes: 1120,
    saves: 589,
    copies: 1580,
    forks: 34,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-03T16:00:00'),
  },
  {
    id: 'prompt6',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video6.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1748483720485-62a341f406e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXJyZWFsJTIwZGlnaXRhbCUyMGFydHxlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Surreal dreamscape with floating geometric shapes slowly rotating in a void of pastel gradients, minimal composition, ethereal atmosphere, smooth camera orbit',
    model: 'Runway',
    contentType: 'video',
    aspectRatio: 'landscape',
    styleTags: ['surreal', 'abstract', 'motion'],
    cameraNotes: 'orbital camera movement, soft focus, minimal lighting',
    moodLabel: 'Surreal',
    difficulty: 'Intermediate',
    likes: 378,
    saves: 201,
    copies: 445,
    forks: 15,
    isForked: true,
    forkedFromId: 'prompt2',
    forkedFromAuthorHandle: 'soramaster',
    createdAt: new Date('2026-04-03T09:30:00'),
  },
  {
    id: 'prompt7',
    authorUid: 'user1',
    authorHandle: 'soramaster',
    authorAvatar: mockUsers[0].avatarUrl,
    videoUrl: 'https://example.com/video7.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529310399831-ed472b81d589?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3J0cmFpdCUyMGZhc2hpb24lMjBtb2RlbHxlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Fashion model walking towards camera in slow motion, flowing fabric billowing behind, dramatic backlighting, vertical frame composition for social media',
    model: 'Sora',
    contentType: 'video',
    aspectRatio: 'portrait',
    styleTags: ['fashion', 'slowmo', 'cinematic'],
    cameraNotes: 'vertical 9:16 format, 120fps slow motion, backlit',
    moodLabel: 'Dramatic',
    difficulty: 'Intermediate',
    likes: 756,
    saves: 389,
    copies: 922,
    forks: 19,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-02T14:30:00'),
  },
  {
    id: 'prompt8',
    authorUid: 'user2',
    authorHandle: 'runwaypro',
    authorAvatar: mockUsers[1].avatarUrl,
    videoUrl: 'https://example.com/video8.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618172193622-ae2d025f4032?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3J0cmFpdCUyMGRhbmNlciUyMG1vdmluZ3xlbnwxfHx8fDE3NzU0NDAwMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    promptText: 'Dancer performing fluid movements in a neon-lit studio, captured in vertical format with dynamic camera tracking, vibrant purple and blue lighting',
    model: 'Runway',
    contentType: 'video',
    aspectRatio: 'portrait',
    styleTags: ['urban', 'motion', 'neon'],
    cameraNotes: 'vertical 9:16 format, tracking shot, colored gels',
    moodLabel: 'Energetic',
    difficulty: 'Advanced',
    likes: 623,
    saves: 298,
    copies: 741,
    forks: 11,
    isForked: false,
    forkedFromId: null,
    forkedFromAuthorHandle: null,
    createdAt: new Date('2026-04-02T10:15:00'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif1',
    userId: 'currentUser',
    type: 'copy',
    fromUid: 'user1',
    fromHandle: 'soramaster',
    fromAvatar: mockUsers[0].avatarUrl,
    promptId: 'prompt1',
    message: '@soramaster copied your prompt — "A sweeping aerial view..."',
    read: false,
    createdAt: new Date('2026-04-06T08:30:00'),
  },
  {
    id: 'notif2',
    userId: 'currentUser',
    type: 'follow',
    fromUid: 'user2',
    fromHandle: 'runwaypro',
    fromAvatar: mockUsers[1].avatarUrl,
    message: '@runwaypro started following you',
    read: false,
    createdAt: new Date('2026-04-05T22:15:00'),
  },
  {
    id: 'notif3',
    userId: 'currentUser',
    type: 'like',
    fromUid: 'user1',
    fromHandle: 'soramaster',
    fromAvatar: mockUsers[0].avatarUrl,
    promptId: 'prompt1',
    message: '@soramaster liked your prompt',
    read: true,
    createdAt: new Date('2026-04-05T16:45:00'),
  },
  {
    id: 'notif4',
    userId: 'currentUser',
    type: 'fork',
    fromUid: 'user2',
    fromHandle: 'runwaypro',
    fromAvatar: mockUsers[1].avatarUrl,
    promptId: 'prompt1',
    message: '@runwaypro forked your prompt — "A sweeping aerial view..."',
    read: true,
    createdAt: new Date('2026-04-04T14:20:00'),
  },
];

export const mockCollections: Collection[] = [
  {
    id: 'collection1',
    userId: 'currentUser',
    name: 'Cinematic',
    description: 'Epic, filmic shots to revisit later.',
    count: 24,
    thumbnails: mockPrompts.slice(0, 4).map((prompt) => prompt.thumbnailUrl),
    createdAt: new Date('2026-04-01T08:00:00'),
  },
  {
    id: 'collection2',
    userId: 'currentUser',
    name: 'Nature',
    description: 'Landscapes and outdoor motion references.',
    count: 18,
    thumbnails: mockPrompts.slice(1, 5).map((prompt) => prompt.thumbnailUrl),
    createdAt: new Date('2026-03-28T08:00:00'),
  },
  {
    id: 'collection3',
    userId: 'currentUser',
    name: 'Abstract',
    description: 'Stylized motion and texture ideas.',
    count: 12,
    thumbnails: mockPrompts.slice(2, 6).map((prompt) => prompt.thumbnailUrl),
    createdAt: new Date('2026-03-20T08:00:00'),
  },
];
